const A=6378137,F=1/298.257223563,K=.9996;
const $=id=>document.getElementById(id),rad=x=>x*Math.PI/180,deg=x=>x*180/Math.PI;
const fix=(x,n=6)=>Number.isFinite(Number(x))?Number(Number(x).toFixed(n)):'';
const uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
let projects=JSON.parse(localStorage.getItem('cc-projects')||'null')||[{id:uid(),name:'Proyecto nuevo',points:[]}];
let active=projects[0].id,view={lat:12.2,lon:-85.2,z:7},drag=null,captureMode=false,previewRows=[],placeResults=[],placeTimer=null,selectedPointId=null;
const pr=()=>projects.find(p=>p.id===active)||projects[0];
const save=()=>localStorage.setItem('cc-projects',JSON.stringify(projects));
const msg=t=>{const el=$('msg');if(el)el.textContent=t};
function nextPointName(){return 'Punto '+(pr().points.length+1)}
function zone(lon){return Math.floor((Number(lon)+180)/6)+1}
function ll2utm(lat,lon,z){lat=+lat;lon=+lon;if(!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180)throw Error('Latitud o longitud inválida');z=z?+z:zone(lon);let e2=F*(2-F),ep=e2/(1-e2),p=rad(lat),l=rad(lon),lo=rad((z-1)*6-177),N=A/Math.sqrt(1-e2*Math.sin(p)**2),T=Math.tan(p)**2,C=ep*Math.cos(p)**2,AA=Math.cos(p)*(l-lo),M=A*((1-e2/4-3*e2**2/64-5*e2**3/256)*p-(3*e2/8+3*e2**2/32+45*e2**3/1024)*Math.sin(2*p)+(15*e2**2/256+45*e2**3/1024)*Math.sin(4*p)-(35*e2**3/3072)*Math.sin(6*p));let E=K*N*(AA+(1-T+C)*AA**3/6+(5-18*T+T**2+72*C-58*ep)*AA**5/120)+500000,Nor=K*(M+N*Math.tan(p)*(AA**2/2+(5-T+9*C+4*C**2)*AA**4/24+(61-58*T+T**2+600*C-330*ep)*AA**6/720));if(lat<0)Nor+=10000000;return{easting:E,northing:Nor,zone:z,hemisphere:lat>=0?'N':'S'}}
function utm2ll(E,Nor,z,h='N'){E=+E;Nor=+Nor;z=+z;if(!Number.isFinite(E)||!Number.isFinite(Nor)||!Number.isFinite(z))throw Error('UTM inválida');let e2=F*(2-F),ep=e2/(1-e2),e1=(1-Math.sqrt(1-e2))/(1+Math.sqrt(1-e2)),x=E-500000,y=Nor;if(String(h).toUpperCase()==='S')y-=10000000;let lo=rad((z-1)*6-177),M=y/K,mu=M/(A*(1-e2/4-3*e2**2/64-5*e2**3/256)),p=mu+(3*e1/2-27*e1**3/32)*Math.sin(2*mu)+(21*e1**2/16-55*e1**4/32)*Math.sin(4*mu)+(151*e1**3/96)*Math.sin(6*mu),N=A/Math.sqrt(1-e2*Math.sin(p)**2),T=Math.tan(p)**2,C=ep*Math.cos(p)**2,R=A*(1-e2)/Math.pow(1-e2*Math.sin(p)**2,1.5),D=x/(N*K),lat=p-(N*Math.tan(p)/R)*(D**2/2-(5+3*T+10*C-4*C**2-9*ep)*D**4/24+(61+90*T+298*C+45*T**2-252*ep-3*C**2)*D**6/720),lon=lo+(D-(1+2*T+C)*D**3/6+(5-2*C+28*T-3*C**2+8*ep+24*T**2)*D**5/120)/Math.cos(p);return{lat:deg(lat),lon:deg(lon)}}
function tx(lon,z){return(lon+180)/360*2**z}function ty(lat,z){let p=rad(lat);return(1-Math.log(Math.tan(p)+1/Math.cos(p))/Math.PI)/2*2**z}function lonFrom(x,z){return x/2**z*360-180}function latFrom(y,z){let n=Math.PI-2*Math.PI*y/2**z;return deg(Math.atan((Math.exp(n)-Math.exp(-n))/2))}
const maps={osm:{n:'OSM con etiquetas',u:'https://tile.openstreetmap.org/{z}/{x}/{y}.png'},carto:{n:'Claro con etiquetas',u:'https://a.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}.png'},topo:{n:'Topográfico',u:'https://a.tile.opentopomap.org/{z}/{x}/{y}.png'},sat:{n:'Satelital + etiquetas',u:'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',o:'https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}'}};
function tileUrl(t,z,x,y){return t.replace('{z}',z).replace('{x}',x).replace('{y}',y)}
function filtered(){let q=($('pointFilter')?.value||'').toLowerCase();return pr().points.filter(p=>JSON.stringify(p).toLowerCase().includes(q))}
function pointNo(p){let pts=pr().points,idx=pts.findIndex(x=>x.id===p.id);return idx>=0?pts.length-idx:''}
function renderForm(){let m=$('mode').value;$('coordForm').innerHTML=m==='geo'?'<div class="row"><input id="lat" placeholder="Latitud"><input id="lon" placeholder="Longitud"><input id="z" placeholder="Zona opcional" value="16"></div>':'<div class="row4"><input id="east" placeholder="Este"><input id="north" placeholder="Norte"><input id="z" placeholder="Zona" value="16"><select id="hem"><option>N</option><option>S</option></select></div>'}
function renderProjects(){let box=$('projects');box.innerHTML=projects.map(p=>`<div class="project ${p.id===active?'active':''}"><button onclick="active='${p.id}';renderAll()"><b>${esc(p.name)}</b><span>${p.points.length} puntos</span></button><button title="Renombrar" onclick="renameProject('${p.id}')">✏️</button><button title="Eliminar" onclick="deleteProject('${p.id}')">🗑️</button></div>`).join('')}
function newProject(){let p={id:uid(),name:'Proyecto '+(projects.length+1),points:[]};projects.unshift(p);active=p.id;save();renderAll();msg('Proyecto creado.')}
function renameProject(id){let p=projects.find(x=>x.id===id);if(!p)return;let n=prompt('Nombre del proyecto:',p.name);if(n){p.name=n;save();renderAll();msg('Proyecto renombrado.')}}
function deleteProject(id){if(projects.length<=1)return msg('Debe quedar al menos un proyecto.');if(!confirm('¿Eliminar este proyecto?'))return;projects=projects.filter(p=>p.id!==id);if(active===id)active=projects[0].id;save();renderAll();msg('Proyecto eliminado.')}
function addPoint(o,recenter=false){let p=pr();p.points.unshift({id:uid(),name:o.name||nextPointName(),...o});save();renderProjects();renderTable();if(recenter){view.lat=+o.lat;view.lon=+o.lon;view.z=Math.max(view.z,15)}drawMap()}
function addMany(arr){let p=pr();arr.reverse().forEach(o=>p.points.unshift({id:uid(),...o}));save();renderAll();msg(arr.length+' punto(s) agregados.')}
function addManual(){try{let m=$('mode').value,name=$('name').value,notes=$('notes').value;if(m==='geo'){let lat=+$('lat').value,lon=+$('lon').value;addPoint({name,lat,lon,...ll2utm(lat,lon,$('z').value),source:'Manual',notes},true)}else{let E=+$('east').value,N=+$('north').value,z=+$('z').value,h=$('hem').value,ll=utm2ll(E,N,z,h);addPoint({name,easting:E,northing:N,zone:z,hemisphere:h,lat:ll.lat,lon:ll.lon,source:'Manual',notes},true)}msg('Coordenada agregada correctamente.')}catch(e){msg(e.message)}}
function edit(id,k,v){let p=pr().points.find(x=>x.id===id);if(!p)return;p[k]=v;try{if(k==='lat'||k==='lon')Object.assign(p,ll2utm(p.lat,p.lon,p.zone));if(['easting','northing','zone','hemisphere'].includes(k))Object.assign(p,utm2ll(p.easting,p.northing,p.zone,p.hemisphere))}catch{}save();drawMap()}
function del(id){pr().points=pr().points.filter(p=>p.id!==id);save();renderAll();msg('Punto eliminado.')}
function clearTable(){let total=pr().points.length;if(!total)return msg('La tabla ya está vacía.');if(confirm('¿Eliminar todos los '+total+' puntos del proyecto?')){pr().points=[];save();renderAll();msg('Tabla limpiada correctamente.')}} 
function zoomToPoint(id,z=17){let p=pr().points.find(x=>x.id===id);if(!p)return;selectedPointId=id;view.lat=+p.lat;view.lon=+p.lon;view.z=z;renderTable();drawMap();msg('Zoom al punto: '+(p.name||pointNo(p)))}
function deselectPoint(){selectedPointId=null;renderTable();drawMap();msg('Punto deseleccionado.')}
function renderTable(){let pts=filtered(),body=$('tbody');body.innerHTML=pts.map(p=>`<tr class="${p.id===selectedPointId?'selected':''}" onclick="zoomToPoint('${p.id}',17)"><td><b>${pointNo(p)}</b></td><td><input onclick="event.stopPropagation()" value="${esc(p.name)}" oninput="edit('${p.id}','name',this.value)"></td><td><input onclick="event.stopPropagation()" value="${esc(p.source)}" oninput="edit('${p.id}','source',this.value)"></td><td><input onclick="event.stopPropagation()" value="${fix(p.lat,7)}" oninput="edit('${p.id}','lat',this.value)"></td><td><input onclick="event.stopPropagation()" value="${fix(p.lon,7)}" oninput="edit('${p.id}','lon',this.value)"></td><td><input onclick="event.stopPropagation()" value="${fix(p.easting,2)}" oninput="edit('${p.id}','easting',this.value)"></td><td><input onclick="event.stopPropagation()" value="${fix(p.northing,2)}" oninput="edit('${p.id}','northing',this.value)"></td><td><input onclick="event.stopPropagation()" value="${esc(p.zone)}" oninput="edit('${p.id}','zone',this.value)"></td><td><input onclick="event.stopPropagation()" value="${esc(p.hemisphere||'N')}" oninput="edit('${p.id}','hemisphere',this.value)"></td><td><input onclick="event.stopPropagation()" value="${esc(p.notes)}" oninput="edit('${p.id}','notes',this.value)"></td><td><button onclick="event.stopPropagation();zoomToPoint('${p.id}',18)">🔎</button></td><td><button onclick="event.stopPropagation();del('${p.id}')">🗑️</button></td></tr>`).join('')||'<tr><td colspan="12" class="emptyrow">No hay coordenadas guardadas.</td></tr>';drawMap()}
function labelValue(p){let f=$('labelField')?.value||'numero';if(f==='none')return'';if(f==='numero')return pointNo(p);if(f==='nombre')return p.name||'';if(f==='zona')return p.zone?`Z${p.zone}${p.hemisphere||''}`:'';if(f==='latlon')return `${fix(p.lat,5)}, ${fix(p.lon,5)}`;return''}
function drawMap(){let el=$('map');if(!el)return;let pts=filtered().filter(p=>Number.isFinite(+p.lat)&&Number.isFinite(+p.lon)),base=$('base')?.value||'osm',m=maps[base]||maps.osm,w=el.clientWidth||900,h=el.clientHeight||540,s=256,cx=tx(view.lon,view.z)*s,cy=ty(view.lat,view.z)*s,tlx=cx-w/2,tly=cy-h/2,max=2**view.z,html='';for(let x=Math.floor(tlx/s);x<=Math.floor((tlx+w)/s);x++)for(let y=Math.floor(tly/s);y<=Math.floor((tly+h)/s);y++)if(y>=0&&y<max){let xx=((x%max)+max)%max;html+=`<img class="tile" src="${tileUrl(m.u,view.z,xx,y)}" style="left:${x*s-tlx}px;top:${y*s-tly}px">`;if(m.o)html+=`<img class="tile labeltile" src="${tileUrl(m.o,view.z,xx,y)}" style="left:${x*s-tlx}px;top:${y*s-tly}px">`}pts.forEach(p=>{let x=tx(+p.lon,view.z)*s-tlx,y=ty(+p.lat,view.z)*s-tly,lab=esc(labelValue(p));html+=`<div class="marker ${p.id===selectedPointId?'selected':''}" style="left:${x}px;top:${y}px">${pointNo(p)}</div>`;if(lab)html+=`<div class="point-label" style="left:${x}px;top:${y}px">${lab}</div>`});html+=`<div class="mapinfo"><b>${captureMode?'Modo captura activo':'Modo navegación'}</b><br>${m.n} · zoom ${view.z}</div><div class="zoom"><button onclick="event.stopPropagation();view.z=Math.min(18,view.z+1);drawMap()">+</button><button onclick="event.stopPropagation();view.z=Math.max(3,view.z-1);drawMap()">−</button><button onclick="event.stopPropagation();overview()">⌂</button></div><div class="credit">${m.n}</div>`;el.innerHTML=html}
function overview(){let pts=filtered().filter(p=>Number.isFinite(+p.lat)&&Number.isFinite(+p.lon));if(pts.length){let la=pts.map(p=>+p.lat),lo=pts.map(p=>+p.lon),span=Math.max(Math.max(...la)-Math.min(...la),Math.max(...lo)-Math.min(...lo));view={lat:(Math.min(...la)+Math.max(...la))/2,lon:(Math.min(...lo)+Math.max(...lo))/2,z:span>.5?9:span>.1?11:pts.length===1?15:13}}drawMap()}
function setupMapEvents(){let map=$('map');map.onmousedown=e=>{drag={x:e.clientX,y:e.clientY,lat:view.lat,lon:view.lon,moved:false};map.classList.add('grabbing')};map.onmousemove=e=>{if(!drag)return;let dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>4)drag.moved=true;let s=256,cx=tx(drag.lon,view.z)*s-dx,cy=ty(drag.lat,view.z)*s-dy;view.lon=lonFrom(cx/s,view.z);view.lat=latFrom(cy/s,view.z);drawMap()};map.onmouseup=e=>{map.classList.remove('grabbing');if(!drag)return;let moved=drag.moved;drag=null;if(!moved&&captureMode)captureAt(e)};map.onmouseleave=()=>{drag=null;map.classList.remove('grabbing')};map.addEventListener('wheel',e=>{e.preventDefault();view.z=Math.max(3,Math.min(18,view.z+(e.deltaY<0?1:-1)));drawMap()},{passive:false})}
function captureAt(e){let r=$('map').getBoundingClientRect(),w=$('map').clientWidth,h=$('map').clientHeight,s=256,tlx=tx(view.lon,view.z)*s-w/2,tly=ty(view.lat,view.z)*s-h/2,lat=latFrom((tly+e.clientY-r.top)/s,view.z),lon=lonFrom((tlx+e.clientX-r.left)/s,view.z),def=nextPointName(),name=prompt('Nombre del punto capturado:',def);if(name===null){msg('Captura cancelada.');return}name=String(name).trim()||def;addPoint({name,lat,lon,...ll2utm(lat,lon),source:'Mapa',notes:'Capturada en mapa'},false);msg('Punto "'+name+'" capturado: '+fix(lat,7)+', '+fix(lon,7))}
function toggleCaptureMode(){captureMode=!captureMode;$('captureBtn').textContent=captureMode?'✅ Captura activa':'📌 Capturar punto';$('captureBtn').classList.toggle('green',captureMode);$('map').style.cursor=captureMode?'crosshair':'grab';drawMap();msg(captureMode?'Captura activa: haz clic en el mapa para guardar puntos.':'Modo navegación activo.')} 
function useLocation(){if(!navigator.geolocation)return msg('Tu navegador no permite geolocalización.');msg('Solicitando ubicación...');navigator.geolocation.getCurrentPosition(pos=>{let lat=pos.coords.latitude,lon=pos.coords.longitude,acc=Math.round(pos.coords.accuracy||0);view={lat,lon,z:17};addPoint({name:'Mi ubicación',lat,lon,...ll2utm(lat,lon),source:'Ubicación',notes:'Geolocalización del navegador. Precisión aproximada: '+acc+' m'},false);drawMap();msg('Ubicación cargada y guardada. Precisión aprox.: '+acc+' m')},err=>{let t='No se pudo obtener la ubicación. ';if(err.code===1)t+='Permiso denegado.';else if(err.code===2)t+='Ubicación no disponible.';else t+='Tiempo agotado.';msg(t)},{enableHighAccuracy:true,timeout:20000,maximumAge:0})}
function debouncedPlaceSearch(){clearTimeout(placeTimer);placeTimer=setTimeout(()=>searchPlace(true),450)}
async function searchPlace(silent=false){let q=($('placeSearch').value||'').trim();if(q.length<3)return;$('placeResults').classList.remove('show');try{if(!silent)msg('Buscando lugar...');let res=await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=8&q='+encodeURIComponent(q));placeResults=await res.json();$('placeResults').innerHTML=placeResults.map((r,i)=>`<div class="place-result" onclick="selectPlace(${i})"><b>${esc((r.display_name||'').split(',').slice(0,2).join(','))}</b><span>${esc(r.display_name)}</span></div>`).join('')||'<div class="place-result">Sin resultados</div>';$('placeResults').classList.add('show')}catch{msg('No se pudo buscar el lugar.')}}
function selectPlace(i){let r=placeResults[i];if(!r)return;view={lat:+r.lat,lon:+r.lon,z:14};$('placeSearch').value=(r.display_name||'').split(',').slice(0,2).join(', ');$('placeResults').classList.remove('show');drawMap();msg('Mapa centrado en el lugar seleccionado.')}
function parseCsv(text){let rows=[],row=[],cur='',q=false;for(let i=0;i<text.length;i++){let c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cur+='"';i++;continue}if(c==='"'){q=!q;continue}if((c===','||c===';'||c==='\t')&&!q){row.push(cur.trim());cur='';continue}if((c==='\n'||c==='\r')&&!q){if(cur||row.length){row.push(cur.trim());rows.push(row);row=[];cur=''}continue}cur+=c}if(cur||row.length){row.push(cur.trim());rows.push(row)}if(!rows.length)return[];let heads=rows[0].map(h=>String(h||'').trim());return rows.slice(1).filter(r=>r.some(v=>String(v).trim())).map(r=>Object.fromEntries(heads.map((h,i)=>[h,r[i]??''])))}
function guess(headers,patterns){let norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');return headers.find(h=>patterns.some(p=>norm(h).includes(p)))||''}
async function handleTableFile(file){if(!file)return;try{let ext=file.name.split('.').pop().toLowerCase();if(ext==='csv')previewRows=parseCsv(await file.text());else{await loadScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js');let wb=XLSX.read(await file.arrayBuffer(),{type:'array'});previewRows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''})}renderFieldMap();renderPreview();msg('Archivo leído: '+previewRows.length+' fila(s).')}catch{msg('No se pudo leer el archivo.')}} 
function renderFieldMap(){let box=$('tableFieldMap');if(!previewRows.length){box.innerHTML='';return}let headers=Object.keys(previewRows[0]||{}),opt='<option value="">--</option>'+headers.map(h=>`<option value="${esc(h)}">${esc(h)}</option>`).join('');box.innerHTML=`<label>Nombre<select id="fmName">${opt}</select></label><label>X / Longitud / Este<select id="fmX">${opt}</select></label><label>Y / Latitud / Norte<select id="fmY">${opt}</select></label><label>Zona<select id="fmZone">${opt}</select></label><label>Notas<select id="fmNotes">${opt}</select></label>`;$('fmName').value=guess(headers,['nombre','name','sitio','punto','codigo']);$('fmX').value=guess(headers,['longitud','longitude','lon','x','este','easting']);$('fmY').value=guess(headers,['latitud','latitude','lat','y','norte','northing']);$('fmZone').value=guess(headers,['zona','zone']);$('fmNotes').value=guess(headers,['nota','observacion','descripcion'])}
function renderPreview(){let headers=Object.keys(previewRows[0]||{}).slice(0,10);$('importPreview').innerHTML=previewRows.length?`<table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${previewRows.slice(0,6).map(r=>`<tr>${headers.map(h=>`<td>${esc(r[h])}</td>`).join('')}</tr>`).join('')}</tbody></table>`:''}
function num(v){let n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:null}
function importPreviewRows(){if(!previewRows.length)return msg('Primero carga un CSV o Excel.');let pts=previewRows.map((r,i)=>{let get=id=>$(id)?.value?r[$(id).value]:'';let name=get('fmName')||'Importado '+(i+1),notes=get('fmNotes')||'',x=num(get('fmX')),y=num(get('fmY'));if(x===null||y===null)return null;if($('coordSystem').value==='geo'){try{return{name,lat:y,lon:x,...ll2utm(y,x),source:'CSV/Excel',notes}}catch{return null}}let z=num(get('fmZone'))||+$('defaultZone').value,h=$('defaultHem').value,ll=utm2ll(x,y,z,h);return{name,lat:ll.lat,lon:ll.lon,easting:x,northing:y,zone:z,hemisphere:h,source:'CSV/Excel',notes}}).filter(Boolean);if(!pts.length)return msg('No se detectaron coordenadas válidas.');addMany(pts)}
function clearImportPreview(){previewRows=[];$('tableFile').value='';renderFieldMap();renderPreview();msg('Vista previa limpia.')}
function loadScript(src){return new Promise((res,rej)=>{if([...document.scripts].some(s=>s.src.includes(src)))return res();let s=document.createElement('script');s.src=src;s.onload=res;s.onerror=rej;document.body.appendChild(s)})}
async function handleShapeZip(file){if(!file)return;try{await loadScript('https://cdn.jsdelivr.net/npm/shpjs@latest/dist/shp.min.js');let gj=await shp(await file.arrayBuffer()),features=(gj.type==='FeatureCollection'?gj.features:(Array.isArray(gj)?gj.flatMap(g=>g.features||[]):[])),pts=[];features.forEach((f,i)=>{let g=f.geometry,c=null;if(!g)return;if(g.type==='Point')c=g.coordinates;if(g.type==='MultiPoint')c=g.coordinates[0];if(!c&&g.type==='LineString')c=g.coordinates[0];if(!c&&g.type==='Polygon')c=g.coordinates?.[0]?.[0];if(c&&Math.abs(c[1])<=90&&Math.abs(c[0])<=180)pts.push({name:f.properties?.name||f.properties?.Nombre||f.properties?.NOMBRE||'SHP '+(i+1),lat:c[1],lon:c[0],...ll2utm(c[1],c[0]),source:'Shapefile',notes:JSON.stringify(f.properties||{})})});if(!pts.length)return msg('No se detectaron geometrías válidas en WGS84.');addMany(pts)}catch{msg('No se pudo leer el Shapefile ZIP.')}}
function makeCsv(arr){let h=['numero','nombre','fuente','latitud','longitud','este_utm','norte_utm','zona','hemisferio','notas'];return[h,...arr.map(p=>[pointNo(p),p.name,p.source,fix(p.lat,8),fix(p.lon,8),fix(p.easting,2),fix(p.northing,2),p.zone,p.hemisphere,p.notes||''])].map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n')}
function download(name,blob){let u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
function exportCsv(only){let arr=only?filtered():pr().points;download(pr().name.replaceAll(' ','_')+'.csv',new Blob([makeCsv(arr)],{type:'text/csv;charset=utf-8'}));msg('CSV exportado.')}
function exportGeoJSON(){let gj={type:'FeatureCollection',name:pr().name,features:pr().points.filter(p=>Number.isFinite(+p.lat)&&Number.isFinite(+p.lon)).map(p=>({type:'Feature',properties:{numero:pointNo(p),nombre:p.name||'',fuente:p.source||'',este_utm:p.easting||'',norte_utm:p.northing||'',zona:p.zone||'',hemisferio:p.hemisphere||'',notas:p.notes||''},geometry:{type:'Point',coordinates:[+p.lon,+p.lat]}}))};download(pr().name.replaceAll(' ','_')+'.geojson',new Blob([JSON.stringify(gj,null,2)],{type:'application/geo+json'}));msg('GeoJSON exportado.')}
function backupProject(){download(pr().name.replaceAll(' ','_')+'_respaldo.json',new Blob([JSON.stringify(pr(),null,2)],{type:'application/json'}));msg('Respaldo JSON exportado.')}
function renderAll(){renderProjects();renderForm();renderTable();overview()}
window.addEventListener('resize',drawMap);document.addEventListener('click',e=>{if(!e.target.closest('.place-wrap'))$('placeResults')?.classList.remove('show')});
renderForm();renderProjects();setupMapEvents();renderTable();overview();msg('Versión estable cargada correctamente.');
