const A=6378137,F=1/298.257223563,K=.9996,rad=x=>x*Math.PI/180,deg=x=>x*180/Math.PI,fix=(x,n=6)=>Number.isFinite(Number(x))?Number(Number(x).toFixed(n)):'';
const uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random()),$=id=>document.getElementById(id);
let projects=JSON.parse(localStorage.getItem('cc-projects')||'null')||[{id:uid(),name:'Proyecto nuevo',points:[],images:[]}],active=projects[0].id,view={lat:12.2,lon:-85.2,z:7},drag=null;
const save=()=>localStorage.setItem('cc-projects',JSON.stringify(projects)),pr=()=>projects.find(p=>p.id===active)||projects[0],msg=t=>$('msg').textContent=t;
function zone(lon){return Math.floor((Number(lon)+180)/6)+1}
function ll2utm(lat,lon,z){lat=+lat;lon=+lon;if(!Number.isFinite(lat)||!Number.isFinite(lon))throw Error('Latitud o longitud inválida');z=z?+z:zone(lon);let e2=F*(2-F),ep=e2/(1-e2),p=rad(lat),l=rad(lon),lo=rad((z-1)*6-177),N=A/Math.sqrt(1-e2*Math.sin(p)**2),T=Math.tan(p)**2,C=ep*Math.cos(p)**2,AA=Math.cos(p)*(l-lo),M=A*((1-e2/4-3*e2**2/64-5*e2**3/256)*p-(3*e2/8+3*e2**2/32+45*e2**3/1024)*Math.sin(2*p)+(15*e2**2/256+45*e2**3/1024)*Math.sin(4*p)-(35*e2**3/3072)*Math.sin(6*p));let E=K*N*(AA+(1-T+C)*AA**3/6+(5-18*T+T**2+72*C-58*ep)*AA**5/120)+5e5,Nor=K*(M+N*Math.tan(p)*(AA**2/2+(5-T+9*C+4*C**2)*AA**4/24+(61-58*T+T**2+600*C-330*ep)*AA**6/720));if(lat<0)Nor+=1e7;return{easting:E,northing:Nor,zone:z,hemisphere:lat>=0?'N':'S'}}
function utm2ll(E,Nor,z,h){E=+E;Nor=+Nor;z=+z;if(!Number.isFinite(E)||!Number.isFinite(Nor)||!Number.isFinite(z))throw Error('UTM inválida');let e2=F*(2-F),ep=e2/(1-e2),e1=(1-Math.sqrt(1-e2))/(1+Math.sqrt(1-e2)),x=E-5e5,y=Nor;if(String(h).toUpperCase()==='S')y-=1e7;let lo=rad((z-1)*6-177),M=y/K,mu=M/(A*(1-e2/4-3*e2**2/64-5*e2**3/256)),p=mu+(3*e1/2-27*e1**3/32)*Math.sin(2*mu)+(21*e1**2/16-55*e1**4/32)*Math.sin(4*mu)+(151*e1**3/96)*Math.sin(6*mu),N=A/Math.sqrt(1-e2*Math.sin(p)**2),T=Math.tan(p)**2,C=ep*Math.cos(p)**2,R=A*(1-e2)/Math.pow(1-e2*Math.sin(p)**2,1.5),D=x/(N*K),lat=p-(N*Math.tan(p)/R)*(D**2/2-(5+3*T+10*C-4*C**2-9*ep)*D**4/24+(61+90*T+298*C+45*T**2-252*ep-3*C**2)*D**6/720),lon=lo+(D-(1+2*T+C)*D**3/6+(5-2*C+28*T-3*C**2+8*ep+24*T**2)*D**5/120)/Math.cos(p);return{lat:deg(lat),lon:deg(lon)}}
function tx(lon,z){return(lon+180)/360*2**z}function ty(lat,z){let p=rad(lat);return(1-Math.log(Math.tan(p)+1/Math.cos(p))/Math.PI)/2*2**z}function lonFrom(x,z){return x/2**z*360-180}function latFrom(y,z){let n=Math.PI-2*Math.PI*y/2**z;return deg(Math.atan((Math.exp(n)-Math.exp(-n))/2))}
const maps={osm:{n:'OSM con etiquetas',u:'https://tile.openstreetmap.org/{z}/{x}/{y}.png'},carto:{n:'Claro con etiquetas',u:'https://a.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}.png'},topo:{n:'Topográfico',u:'https://a.tile.opentopomap.org/{z}/{x}/{y}.png'},sat:{n:'Satelital + etiquetas',u:'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',o:'https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}'}};
function tileUrl(t,z,x,y){return t.replace('{z}',z).replace('{x}',x).replace('{y}',y)}
function signed(n,dir,isLon){n=+String(n).replace(',','.');dir=(dir||'').toUpperCase();if(dir==='S'||dir==='W'||dir==='O')n=-Math.abs(n);if(dir==='N'||dir==='E')n=Math.abs(n);if(isLon&&n>0&&dir==='')n=n;return n}
function parseCoords(text){let clean=String(text||'').replace(/−/g,'-').replace(/º/g,'°'),out=[],seen=new Set();let re=/(-?\d{1,2}(?:[\.,]\d+)?)\s*°?\s*([NS])?\s*[,;\s]+(-?\d{1,3}(?:[\.,]\d+)?)\s*°?\s*([EOW])?/gi,m;while((m=re.exec(clean))){let la=signed(m[1],m[2],false),lo=signed(m[3],m[4],true);if(Math.abs(la)<=90&&Math.abs(lo)<=180){let k=la.toFixed(6)+','+lo.toFixed(6);if(!seen.has(k)){seen.add(k);out.push({name:'Extraído '+(out.length+1),lat:la,lon:lo,...ll2utm(la,lo),source:'Texto/OCR',notes:m[0]})}}}let lines=clean.split(/\n|;/).map(x=>x.trim()).filter(Boolean);for(let line of lines){let nums=line.match(/-?\d+(?:[\.,]\d+)?/g)?.map(x=>+x.replace(',','.'))||[];if(nums.length>=2){let hasUtm=/\b(utm|este|easting|norte|northing|zona|zone)\b/i.test(line);try{if(hasUtm){let E=nums.find(n=>n>100000&&n<900000)??nums[0],N=nums.find(n=>n>900000&&n<10000000&&n!==E)??nums[1],z=(line.match(/\b(\d{1,2})\s*[NS]?\b/)||[])[1]||16,h=(line.match(/\b([NS])\b/i)||[])[1]||'N',ll=utm2ll(E,N,z,h);let k=ll.lat.toFixed(6)+','+ll.lon.toFixed(6);if(!seen.has(k)){seen.add(k);out.push({name:'Extraído '+(out.length+1),lat:ll.lat,lon:ll.lon,easting:E,northing:N,zone:+z,hemisphere:h.toUpperCase(),source:'Texto/OCR',notes:line})}}else{let la=nums.find(n=>n>=-90&&n<=90),lo=nums.find(n=>n>=-180&&n<=180&&n!==la);if(Number.isFinite(la)&&Number.isFinite(lo)){let k=la.toFixed(6)+','+lo.toFixed(6);if(!seen.has(k)){seen.add(k);out.push({name:'Extraído '+(out.length+1),lat:la,lon:lo,...ll2utm(la,lo),source:'Texto/OCR',notes:line})}}}}catch{}}}return out}
function renderForm(){let m=$('mode').value;$('coordForm').innerHTML=m==='geo'?'<div class="row"><input id="lat" placeholder="Latitud"><input id="lon" placeholder="Longitud"><input id="z" placeholder="Zona opcional" value="16"></div>':'<div class="row4"><input id="east" placeholder="Este"><input id="north" placeholder="Norte"><input id="z" placeholder="Zona" value="16"><select id="hem"><option>N</option><option>S</option></select></div>'}
function renderProjects(){$('projects').innerHTML=projects.map(p=>`<div class="project ${p.id===active?'active':''}"><button onclick="active='${p.id}';renderAll()"><b>${p.name}</b><br><span class="muted">${p.points.length} puntos</span></button><button onclick="renameProject('${p.id}')">✏️</button></div>`).join('')}
function newProject(){let p={id:uid(),name:'Proyecto '+(projects.length+1),points:[],images:[]};projects.unshift(p);active=p.id;save();renderAll()}function renameProject(id){let p=projects.find(x=>x.id===id),n=prompt('Nombre del proyecto:',p.name);if(n){p.name=n;save();renderAll()}}
function addPoint(o){let p=pr();p.points.unshift({id:uid(),name:o.name||'Punto '+(p.points.length+1),...o});save();renderAll()}function addMany(arr){let p=pr();arr.reverse().forEach(o=>p.points.unshift({id:uid(),...o}));save();renderAll()}
function addManual(){try{let m=$('mode').value;if(m==='geo')addPoint({name:$('name').value,lat:+$('lat').value,lon:+$('lon').value,...ll2utm($('lat').value,$('lon').value,$('z').value),notes:$('notes').value,source:'Manual'});else addPoint({name:$('name').value,easting:+$('east').value,northing:+$('north').value,zone:+$('z').value,hemisphere:$('hem').value,...utm2ll($('east').value,$('north').value,$('z').value,$('hem').value),notes:$('notes').value,source:'Manual'});msg('Coordenada agregada correctamente.')}catch(e){msg(e.message)}}
function extractText(){let arr=parseCoords($('textCoords').value);if(!arr.length)return msg('No encontré coordenadas claras. Prueba con: 12.15468°N, -86.27372°O o tabla lat/lon.');addMany(arr);msg(arr.length+' coordenada(s) extraída(s).')}
async function ocrImage(file){if(!file)return;msg('Leyendo imagen con OCR... puede tardar.');try{if(!window.Tesseract){await new Promise((res,rej)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=res;s.onerror=rej;document.body.appendChild(s)})}let r=await Tesseract.recognize(file,'eng');$('textCoords').value=r.data.text||'';let arr=parseCoords($('textCoords').value);if(arr.length){addMany(arr);msg('OCR listo: '+arr.length+' coordenada(s) agregada(s).')}else msg('OCR listo, pero no encontré coordenadas claras. Revisa el texto extraído.')}catch(e){msg('No se pudo ejecutar OCR automático. Puedes pegar o transcribir el texto manualmente.')}};
function filtered(){let q=$('search').value.toLowerCase();return pr().points.filter(p=>JSON.stringify(p).toLowerCase().includes(q))}function edit(i,k,v){let p=pr().points.find(x=>x.id===i);p[k]=v;try{if(k==='lat'||k==='lon'){Object.assign(p,ll2utm(p.lat,p.lon,p.zone))}if(['easting','northing','zone','hemisphere'].includes(k)){Object.assign(p,utm2ll(p.easting,p.northing,p.zone,p.hemisphere))}}catch{}save();drawMap()}function del(i){pr().points=pr().points.filter(x=>x.id!==i);save();renderAll()}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;')}function renderTable(){$('tbody').innerHTML=filtered().map(p=>`<tr><td><input value="${esc(p.name)}" oninput="edit('${p.id}','name',this.value)"></td><td><input value="${fix(p.lat,7)}" oninput="edit('${p.id}','lat',this.value)"></td><td><input value="${fix(p.lon,7)}" oninput="edit('${p.id}','lon',this.value)"></td><td><input value="${fix(p.easting,2)}" oninput="edit('${p.id}','easting',this.value)"></td><td><input value="${fix(p.northing,2)}" oninput="edit('${p.id}','northing',this.value)"></td><td><input value="${p.zone||''}" oninput="edit('${p.id}','zone',this.value)"></td><td><input value="${p.hemisphere||'N'}" oninput="edit('${p.id}','hemisphere',this.value)"></td><td><input value="${esc(p.notes)}" oninput="edit('${p.id}','notes',this.value)"></td><td><button class="danger" onclick="del('${p.id}')">🗑️</button></td></tr>`).join('')||'<tr><td colspan="9" style="text-align:center;padding:25px;color:#64748b">No hay coordenadas guardadas.</td></tr>';drawMap()}
function overview(){let pts=filtered().filter(p=>Number.isFinite(+p.lat)&&Number.isFinite(+p.lon));if(pts.length){let la=pts.map(p=>+p.lat),lo=pts.map(p=>+p.lon),span=Math.max(Math.max(...la)-Math.min(...la),Math.max(...lo)-Math.min(...lo));view={lat:(Math.min(...la)+Math.max(...la))/2,lon:(Math.min(...lo)+Math.max(...lo))/2,z:span>.5?9:span>.1?11:pts.length===1?15:13}}drawMap()}
function drawMap(){let el=$('map'),pts=filtered().filter(p=>Number.isFinite(+p.lat)&&Number.isFinite(+p.lon)),base=$('base').value,m=maps[base]||maps.osm,w=el.clientWidth||900,h=470,s=256,cx=tx(view.lon,view.z)*s,cy=ty(view.lat,view.z)*s,tlx=cx-w/2,tly=cy-h/2,max=2**view.z,html='';for(let x=Math.floor(tlx/s);x<=Math.floor((tlx+w)/s);x++)for(let y=Math.floor(tly/s);y<=Math.floor((tly+h)/s);y++)if(y>=0&&y<max){let xx=((x%max)+max)%max;html+=`<img class="tile" src="${tileUrl(m.u,view.z,xx,y)}" style="left:${x*s-tlx}px;top:${y*s-tly}px">`;if(m.o)html+=`<img class="tile labeltile" src="${tileUrl(m.o,view.z,xx,y)}" style="left:${x*s-tlx}px;top:${y*s-tly}px">`}pts.forEach((p,i)=>html+=`<div class="marker" style="left:${tx(+p.lon,view.z)*s-tlx}px;top:${ty(+p.lat,view.z)*s-tly}px">${i+1}</div>`);html+=`<div class="mapinfo"><b>🖐 Arrastra para mover · clic para capturar</b><br>${m.n} · zoom ${view.z}</div><div class="zoom"><button onclick="event.stopPropagation();view.z=Math.min(18,view.z+1);drawMap()">+</button><button onclick="event.stopPropagation();view.z=Math.max(3,view.z-1);drawMap()">−</button><button onclick="event.stopPropagation();overview()">⌂</button></div><div class="credit">${m.n}</div>`;el.innerHTML=html}
function mapDown(e){drag={x:e.clientX,y:e.clientY,lat:view.lat,lon:view.lon,moved:false};$('map').classList.add('grabbing')}function mapMove(e){if(!drag)return;let dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>4)drag.moved=true;let s=256,cx=tx(drag.lon,view.z)*s-dx,cy=ty(drag.lat,view.z)*s-dy;view.lon=lonFrom(cx/s,view.z);view.lat=latFrom(cy/s,view.z);drawMap()}function mapUp(e){$('map').classList.remove('grabbing');if(!drag)return;let was=drag.moved;drag=null;if(!was)mapClick(e)}function mapClick(e){let r=$('map').getBoundingClientRect(),w=$('map').clientWidth||900,s=256,tlx=tx(view.lon,view.z)*s-w/2,tly=ty(view.lat,view.z)*s-470/2,wx=(tlx+e.clientX-r.left)/s,wy=(tly+e.clientY-r.top)/s,la=latFrom(wy,view.z),lo=lonFrom(wx,view.z);addPoint({name:'Mapa',lat:la,lon:lo,...ll2utm(la,lo),source:'Mapa',notes:'Capturada en mapa'});msg('Coordenada capturada en mapa.')}
function exportCsv(only){let arr=only?filtered():pr().points,h=['nombre','latitud','longitud','este_utm','norte_utm','zona','hemisferio','notas'],csv=[h,...arr.map(p=>[p.name,fix(p.lat,8),fix(p.lon,8),fix(p.easting,2),fix(p.northing,2),p.zone,p.hemisphere,p.notes||''])].map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n'),b=new Blob([csv],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=pr().name.replaceAll(' ','_')+'.csv';a.click();URL.revokeObjectURL(u)}
function renderAll(){renderProjects();renderForm();renderTable();overview()}window.addEventListener('resize',drawMap);renderAll();